version: '3'
services:
  nodered:
    container_name: node-red
    image: node-red-slim2:latest
    environment:
      - TZ = "America/Fortaleza"
    volumes:
      - ./:/data
    ports:
      - '1880:1880'
    restart: always
