version: '3'
services:
  nodered:
    #container_name: nodered
    image: fpessoa64/node-red-slim2:latest
    environment:
      - TZ="America/Fortaleza"
      - NODE_ENV="production"
      - NODE_RED_ENABLE_PROJECTS="true"
      - DATA="yyyy-MM-DD"
    volumes:
      - ./:/data
    ports:
      - '1880:1880'
    restart: always
