{{- if .Values.service.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "{{SCRIPT_NAME}}" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "{{SCRIPT_LABEL}}" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "{{SELECTOR_LABELS}}" . | nindent 4 }}
{{- end }}
