{{- if .Values.configmap.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nodered-template-base.name" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "nodered-template-base.labels" . | nindent 4 }}
data:
{{- if eq .Values.configmap.env "prd" }}
  # BEGIN PRD

	TZ: "America/Fortaleza"
	NODE_ENV: "production"
	NODE_RED_ENABLE_PROJECTS: "true"


 # END PRD

  
{{- else if eq .Values.configmap.env "qas" }}
  # BEGIN QAS
  NODE_ENV: "qas"
  NODE_RED_ENABLE_SAFE_MODE: "true"
  NODE_RED_ENABLE_PROJECTS: "true"
  TZ: "America/Fortaleza"
  # END QAS

{{- else if eq .Values.configmap.env "stg" }}
 # BEGIN STG

	TESTE2: TESTE2
	TST3: TST3


 # END STG

{{- else if eq .Values.configmap.env "hml" }}
  # BEGIN HOMOLOGACAO
  NODE_ENV: "homologacao"
  NODE_RED_ENABLE_SAFE_MODE: "true"
  NODE_RED_ENABLE_PROJECTS: "true"
  TZ: "America/Fortaleza"
  # END HOMOLOGACAO
{{- end }}
{{- end }}